const packages = [
  {
    title: "Swiss Alps Explorer",
    country: "Switzerland",
    duration: "8 Days / 7 Nights",
    price: 98000,
    destinations: ["Zurich", "Lucerne", "Interlaken", "Jungfraujoch"],
    images: [
      "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1491557345352-5929e343eb89?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Zurich",
      "Zurich city highlights and old town",
      "Lucerne lake cruise and local tours",
      "Transfer to Interlaken and evening leisure",
      "Jungfraujoch day excursion",
      "Adventure and optional mountain activities",
      "Shopping and return to Zurich",
      "Departure to Bengaluru",
    ],
    description: "A premium alpine escape covering top Swiss mountain and lake towns.",
  },
  {
    title: "Bali Tropical Retreat",
    country: "Indonesia",
    duration: "7 Days / 6 Nights",
    price: 62000,
    destinations: ["Kuta", "Ubud", "Nusa Dua", "Tanah Lot"],
    images: [
      "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1518544866330-95a2f2dd2f4d?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1555400113-49672c8dd54e?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Bali",
      "Kuta beachside leisure",
      "Uluwatu temple and cultural performance",
      "Transfer to Ubud and rice terrace visit",
      "Waterfall and countryside exploration",
      "Nusa Dua water activities and Tanah Lot sunset",
      "Return journey to Bengaluru",
    ],
    description: "A balanced Bali itinerary with beach, culture, and nature.",
  },
  {
    title: "Dubai Luxury Escape",
    country: "UAE",
    duration: "5 Days / 4 Nights",
    price: 75000,
    destinations: ["Dubai Marina", "Burj Khalifa", "Desert Camp", "Palm Jumeirah"],
    images: [
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1526495124232-a04e1849168c?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Flight from Bengaluru and evening at Dubai Marina",
      "Dubai city tour and Burj Khalifa",
      "Desert safari with dinner and shows",
      "Palm Jumeirah and leisure shopping",
      "Return flight to Bengaluru",
    ],
    description: "Modern city luxury combined with iconic experiences.",
  },
  {
    title: "Thailand Highlights",
    country: "Thailand",
    duration: "6 Days / 5 Nights",
    price: 52000,
    destinations: ["Bangkok", "Pattaya", "Coral Island", "Floating Market"],
    images: [
      "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Bangkok",
      "Transfer to Pattaya and city walk",
      "Coral Island speedboat tour",
      "Transfer to Bangkok and temple circuit",
      "Floating market and shopping district",
      "Return to Bengaluru",
    ],
    description: "A value-packed itinerary across Thailand's top attractions.",
  },
  {
    title: "Maldives Island Bliss",
    country: "Maldives",
    duration: "5 Days / 4 Nights",
    price: 115000,
    destinations: ["Male", "Maafushi", "Private Resort Island"],
    images: [
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Male",
      "Speedboat transfer and snorkeling",
      "Sandbank visit and sunset cruise",
      "Resort day and spa sessions",
      "Return to Bengaluru",
    ],
    description: "An indulgent island holiday with marine experiences and relaxation.",
  },
  {
    title: "Japan Sakura Trails",
    country: "Japan",
    duration: "9 Days / 8 Nights",
    price: 129000,
    destinations: ["Tokyo", "Mt. Fuji", "Kyoto", "Osaka"],
    images: [
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Tokyo",
      "Tokyo city districts and culture walk",
      "Tokyo attractions and shopping",
      "Mt. Fuji and Hakone excursion",
      "Shinkansen to Kyoto",
      "Kyoto temples and heritage route",
      "Transfer to Osaka and city highlights",
      "Free day in Osaka",
      "Return to Bengaluru",
    ],
    description: "A fast-paced Japan route covering modern cities and heritage.",
  },
  {
    title: "Vietnam Culture Route",
    country: "Vietnam",
    duration: "7 Days / 6 Nights",
    price: 58000,
    destinations: ["Hanoi", "Halong Bay", "Da Nang", "Hoi An"],
    images: [
      "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1524911782880-5ecf6f0d3f7f?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Hanoi",
      "Hanoi old quarter and street food tour",
      "Halong Bay cruise",
      "Flight to Da Nang and evening leisure",
      "Bana Hills day trip",
      "Hoi An ancient town trail",
      "Return to Bengaluru",
    ],
    description: "Culture, coast, and cuisine blended in one route.",
  },
  {
    title: "Singapore Family Fun",
    country: "Singapore",
    duration: "5 Days / 4 Nights",
    price: 69000,
    destinations: ["Marina Bay", "Sentosa", "Universal Studios", "Gardens by the Bay"],
    images: [
      "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1508962914676-134849a727f0?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1565967511849-76a60a516170?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Singapore",
      "City tour and Gardens by the Bay",
      "Universal Studios full day",
      "Sentosa attractions and leisure",
      "Return to Bengaluru",
    ],
    description: "Family-friendly urban holiday with world-class attractions.",
  },
  {
    title: "Europe Grand Sampler",
    country: "Multi Country",
    duration: "10 Days / 9 Nights",
    price: 142000,
    destinations: ["Paris", "Brussels", "Amsterdam"],
    images: [
      "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Paris",
      "Paris city highlights and Seine cruise",
      "Louvre and cultural districts",
      "Transfer to Brussels",
      "Brussels landmarks and food trail",
      "Transfer to Amsterdam",
      "Canal cruise and museum quarter",
      "Countryside excursion",
      "Shopping and leisure",
      "Return to Bengaluru",
    ],
    description: "A compact Europe sampler through three signature cities.",
  },
  {
    title: "Australia Coastal Journey",
    country: "Australia",
    duration: "8 Days / 7 Nights",
    price: 136000,
    destinations: ["Sydney", "Blue Mountains", "Gold Coast", "Brisbane"],
    images: [
      "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1506973035872-a4f23ef6e624?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1524293581917-878a6d017c71?auto=format&fit=crop&w=1400&q=80",
    ],
    itinerary: [
      "Departure from Bengaluru and arrival in Sydney",
      "Sydney harbour and city landmarks",
      "Blue Mountains day trip",
      "Flight to Gold Coast",
      "Theme park and beach activities",
      "Transfer to Brisbane",
      "Brisbane city leisure",
      "Return to Bengaluru",
    ],
    description: "A coast-focused Australian tour with urban and scenic stops.",
  },
];

module.exports = packages;
